name: Sync images

on:
  workflow_dispatch:

env:
  UPSTREAM_OWNER: RinLit-233-shiroko
  UPSTREAM_REPO: Rin-sHub
  UPSTREAM_PATH: updates/images
  LOCAL_DIR: images

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Fetch upstream file list
        id: fetch-upstream
        run: |
          curl -sL \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ env.UPSTREAM_OWNER }}/${{ env.UPSTREAM_REPO }}/git/trees/main?recursive=1" \
            > tree.json

          jq -r '
            .tree[] |
            select(.type == "blob") |
            select(.path | startswith("${{ env.UPSTREAM_PATH }}/")) |
            select(.path | test("\\.(png|jpe?g|gif|svg|webp|bmp|ico)$"; "i")) |
            .path
          ' tree.json | sort > upstream.list

          echo "Upstream image count: $(wc -l < upstream.list)"

      - name: Build local file list
        run: |
          mkdir -p "${{ env.LOCAL_DIR }}"
          cd "${{ env.LOCAL_DIR }}"

          find . -type f | sed 's|^\./||' | while read -r file; do
            echo "${{ env.UPSTREAM_PATH }}/$file"
          done | sort > ../local.list

          cd ..
          echo "Local image count: $(wc -l < local.list)"

      - name: Find images to download
        id: diff
        run: |
          comm -23 upstream.list local.list > download.list
          echo "Files to download: $(wc -l < download.list)"
          echo "files_to_download=$(jq -Rsc 'split("\n") | .[:-1]' download.list)" >> $GITHUB_OUTPUT

      - name: Download new images
        if: steps.diff.outputs.files_to_download != '[]'
        shell: bash
        run: |
          echo '${{ steps.diff.outputs.files_to_download }}' | jq -r '.[]' | while IFS= read -r rel_path; do
            local_rel_path="${rel_path#${{ env.UPSTREAM_PATH }}/}"
            local_path="${{ env.LOCAL_DIR }}/${local_rel_path}"
            mkdir -p "$(dirname "$local_path")"

            # URL-encode 路径
            encoded_path=$(printf '%s' "$rel_path" | jq -sRr @uri)

            echo "Downloading $rel_path -> $local_path"
            if curl --fail -sL -o "$local_path" \
               "https://raw.githubusercontent.com/${{ env.UPSTREAM_OWNER }}/${{ env.UPSTREAM_REPO }}/main/${encoded_path}"; then
              echo "✅ OK"
            else
              echo "⚠️  Failed / not found, skipped: $rel_path"
            fi
          done

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "${{ env.LOCAL_DIR }}"
          if ! git diff --cached --quiet; then
            git commit -m "Incremental sync: Sync images at $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
            git push
          else
            echo "No new images to commit."
          fi